import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Load environment variables from .env
let pluginDir = null;
const envPath = "./.env";

try {
	if (fs.existsSync(envPath)) {
		const envContent = fs.readFileSync(envPath, "utf8");
		const env = {};
		envContent.split(/\r?\n/).forEach(line => {
			const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
			if (match) {
				let key = match[1];
				let value = match[2] || "";
				if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
				else if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
				env[key] = value.trim();
			}
		});
		pluginDir = env.OBSIDIAN_PLUGIN_DIR;
	}
} catch (e) {
	console.error("[deploy] Failed to read .env file:", e);
}

if (!pluginDir) {
	console.error("❌ [deploy] Error: OBSIDIAN_PLUGIN_DIR is not defined in your .env file.");
	console.error("Please create a '.env' file from '.env.example' and configure OBSIDIAN_PLUGIN_DIR.");
	process.exit(1);
}

// esbuild plugin to copy built files to the Obsidian plugin directory
const deployPlugin = {
	name: "deploy-plugin",
	setup(build) {
		build.onEnd(() => {
			if (!pluginDir) {
				console.log("[deploy] No obsidianPluginDir specified. Skipping deployment.");
				return;
			}

			try {
				if (!fs.existsSync(pluginDir)) {
					fs.mkdirSync(pluginDir, { recursive: true });
					console.log(`[deploy] Created directory: ${pluginDir}`);
				}

				// Copy main.js
				if (fs.existsSync("main.js")) {
					fs.copyFileSync("main.js", path.join(pluginDir, "main.js"));
				}
				// Copy manifest.json
				if (fs.existsSync("manifest.json")) {
					fs.copyFileSync("manifest.json", path.join(pluginDir, "manifest.json"));
				}
				// Copy styles.css if it exists
				if (fs.existsSync("styles.css")) {
					fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
				}
				console.log(`[deploy] Successfully deployed build files to: ${pluginDir}`);
			} catch (err) {
				console.error("[deploy] Failed to deploy files:", err);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
